# Generated by Django 2.0.2 on 2018-02-12 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('sku_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sku_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('sub_category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sub_category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory_SKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Sku')),
                ('sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Subcategory')),
            ],
        ),
    ]
